name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v1
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: './out'

      - name: Deploy the project
        id: deployment
        uses: actions/deploy-pages@v4
